import React from 'react';
import {
  Box,
  Chip,
  Divider,
  LinearProgress,
  Paper,
  Stack,
  Typography,
} from '@mui/material';
import {
  AccountTreeRounded,
  ArrowForwardRounded,
  HubRounded,
  PrecisionManufacturingRounded,
} from '@mui/icons-material';
import { PredictionLabel, SensorData } from '../types';
import { sensorConfig } from '../config/sensorConfig';

interface Props {
  prediction?: PredictionLabel;
  confidence?: number;
  sensorData?: SensorData;
}

type ChipColor = 'default' | 'success' | 'warning' | 'error' | 'info';

const getScenario = (prediction?: PredictionLabel) => {
  switch (prediction) {
    case 'Warning':
      return {
        machineAState: 'Early warning pattern',
        peerState: 'Elevated monitoring',
        fleetState: 'Potential shared risk pattern',
        chipColor: 'warning' as ChipColor,
        sharedInsight:
          'Machine A detected an early warning pattern. Similar machines should monitor hydraulic pressure and oil temperature.',
        eventLog: [
          'Local prediction generated by Machine A',
          'Early warning packaged as shared federation event',
          'Peer DTs update monitoring priority',
          'Fleet DT marks potential shared risk pattern',
        ],
        aggregateRisk: 58,
      };
    case 'Maintenance Required':
      return {
        machineAState: 'Maintenance-critical pattern',
        peerState: 'Risk comparison recommended',
        fleetState: 'System-level maintenance risk increased',
        chipColor: 'error' as ChipColor,
        sharedInsight:
          'Machine A detected a maintenance-critical pattern. Peer DTs should compare current telemetry against the same fault signature.',
        eventLog: [
          'Local prediction generated by Machine A',
          'Critical pattern packaged as shared federation event',
          'Peer DTs prepare risk comparison',
          'Fleet DT increases aggregate maintenance risk',
        ],
        aggregateRisk: 84,
      };
    case 'Normal':
    default:
      return {
        machineAState: prediction ? 'Normal operating pattern' : 'Awaiting local prediction',
        peerState: prediction ? 'Monitoring' : 'Standing by',
        fleetState: prediction ? 'Stable' : 'Awaiting telemetry',
        chipColor: prediction ? ('success' as ChipColor) : ('default' as ChipColor),
        sharedInsight: prediction
          ? 'No anomaly pattern currently propagated.'
          : 'Run a local prediction to generate a conceptual federation event.',
        eventLog: prediction
          ? [
              'Local prediction generated by Machine A',
              'Normal-state insight prepared for federation view',
              'Peer DTs remain in monitoring mode',
              'Fleet DT keeps aggregate status stable',
            ]
          : [
              'Waiting for Machine A local prediction',
              'No shared federation event generated yet',
              'Peer DTs remain in baseline monitoring',
              'Fleet DT awaiting aggregate risk update',
            ],
        aggregateRisk: prediction ? 18 : 0,
      };
  }
};

const formatConfidence = (confidence?: number) => {
  if (confidence === undefined) {
    return 'Pending';
  }

  return `${(confidence * 100).toFixed(1)}%`;
};

function TwinNode({
  title,
  subtitle,
  status,
  color,
  icon,
}: {
  title: string;
  subtitle: string;
  status: string;
  color: ChipColor;
  icon: React.ReactNode;
}) {
  return (
    <Box
      sx={{
        border: '1px solid rgba(0, 0, 0, 0.08)',
        borderRadius: 2,
        p: 1.5,
        minWidth: 0,
      }}
    >
      <Stack direction="row" spacing={1.25} alignItems="flex-start">
        <Box sx={{ color: 'text.secondary', mt: 0.25 }}>{icon}</Box>
        <Box sx={{ minWidth: 0, flex: 1 }}>
          <Typography variant="subtitle2" noWrap>
            {title}
          </Typography>
          <Typography variant="caption" color="text.secondary" display="block">
            {subtitle}
          </Typography>
          <Chip
            label={status}
            size="small"
            color={color}
            sx={{ mt: 1, maxWidth: '100%' }}
          />
        </Box>
      </Stack>
    </Box>
  );
}

function FederatedDigitalTwinsPanel({
  prediction,
  confidence,
  sensorData,
}: Props): React.ReactElement {
  const scenario = getScenario(prediction);
  const pressure = sensorData?.Hydraulic_Pressure;
  const oilTemp = sensorData?.Hydraulic_Oil_Temperature;

  return (
    <Paper sx={{ p: 3 }}>
      <Stack spacing={2}>
        <Box>
          <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 0.5 }}>
            <HubRounded color="primary" fontSize="small" />
            <Typography variant="h6">
              Federated Digital Twins
            </Typography>
          </Stack>
          <Typography variant="body2" color="text.secondary">
            Conceptual federation simulation showing how one local Digital Twin insight could propagate into peer comparison and fleet monitoring.
          </Typography>
        </Box>

        <TwinNode
          title="Machine A"
          subtitle="Local Harvester DT"
          status={scenario.machineAState}
          color={scenario.chipColor}
          icon={<PrecisionManufacturingRounded fontSize="small" />}
        />

        <Stack direction="row" spacing={1} alignItems="center" justifyContent="center">
          <ArrowForwardRounded fontSize="small" color="disabled" />
          <Chip label="shared insight" size="small" variant="outlined" />
          <ArrowForwardRounded fontSize="small" color="disabled" />
        </Stack>

        <Stack spacing={1.25}>
          <TwinNode
            title="Machine B"
            subtitle="Peer Harvester DT"
            status={scenario.peerState}
            color={prediction === 'Normal' ? 'info' : scenario.chipColor}
            icon={<PrecisionManufacturingRounded fontSize="small" />}
          />
          <TwinNode
            title="Machine C"
            subtitle="Peer Harvester DT"
            status={scenario.peerState}
            color={prediction === 'Normal' ? 'info' : scenario.chipColor}
            icon={<PrecisionManufacturingRounded fontSize="small" />}
          />
          <TwinNode
            title="Fleet/System DT"
            subtitle="Aggregated federation view"
            status={scenario.fleetState}
            color={scenario.chipColor}
            icon={<AccountTreeRounded fontSize="small" />}
          />
        </Stack>

        <Box>
          <Typography variant="subtitle2" gutterBottom>
            Shared Insight
          </Typography>
          <Typography variant="body2" color="text.secondary">
            {scenario.sharedInsight}
          </Typography>
          <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap sx={{ mt: 1.5 }}>
            <Chip label={`Local: ${prediction || 'Pending'}`} size="small" color={scenario.chipColor} />
            <Chip label={`Confidence: ${formatConfidence(confidence)}`} size="small" variant="outlined" />
            {pressure !== undefined && (
              <Chip
                label={`${sensorConfig.Hydraulic_Pressure.label}: ${pressure.toFixed(1)} ${sensorConfig.Hydraulic_Pressure.unit}`}
                size="small"
                variant="outlined"
              />
            )}
            {oilTemp !== undefined && (
              <Chip
                label={`${sensorConfig.Hydraulic_Oil_Temperature.label}: ${oilTemp.toFixed(1)} ${sensorConfig.Hydraulic_Oil_Temperature.unit}`}
                size="small"
                variant="outlined"
              />
            )}
          </Stack>
        </Box>

        <Box>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 0.75 }}>
            <Typography variant="subtitle2">
              Aggregate Risk Signal
            </Typography>
            <Typography variant="body2" sx={{ fontWeight: 600 }}>
              {scenario.aggregateRisk}%
            </Typography>
          </Box>
          <LinearProgress
            variant="determinate"
            value={scenario.aggregateRisk}
            color={scenario.chipColor === 'error' ? 'error' : scenario.chipColor === 'warning' ? 'warning' : 'success'}
            sx={{ height: 6, borderRadius: 3 }}
          />
        </Box>

        <Divider />

        <Box>
          <Typography variant="subtitle2" gutterBottom>
            Federation Event Log
          </Typography>
          <Stack spacing={0.75}>
            {scenario.eventLog.map((event, index) => (
              <Box key={event} sx={{ display: 'flex', gap: 1 }}>
                <Typography variant="caption" sx={{ color: 'text.secondary', minWidth: 18 }}>
                  {index + 1}.
                </Typography>
                <Typography variant="caption" color="text.secondary">
                  {event}
                </Typography>
              </Box>
            ))}
          </Stack>
        </Box>
      </Stack>
    </Paper>
  );
}

export default FederatedDigitalTwinsPanel;
